/* made by EzioChiu
   Image: /System/Library/PrivateFrameworks/Sharing.framework/Sharing
 */

@interface SFDeviceSetupB238Session : NSObject <AVAudioPlayerDelegate> {
    bool  _acpSecured;
    bool  _activateCalled;
    NSDictionary * _additionalMetrics;
    bool  _apcEnabled;
    bool  _apcInitDone;
    APCListener * _apcListener;
    NSString * _apcPasscode;
    bool  _apcPlayAgain;
    bool  _apcPlaying;
    bool  _apcSkip;
    bool  _apcStartDone;
    bool  _apcStartedPairSetup;
    int  _apcState;
    bool  _apcSupported;
    NSObject<OS_dispatch_source> * _apcTimer;
    bool  _apcTryingPasscode;
    bool  _appleMusicEnabled;
    id /* block */  _audioPlayerCompletion;
    AVAudioPlayer * _audioPlayerStart;
    AVAudioPlayer * _audioPlayerStep;
    bool  _audioProgress;
    AVAudioSession * _audioSession;
    double  _basicConfigSecs;
    unsigned long long  _basicConfigStartTicks;
    int  _basicConfigState;
    NSString * _deviceGUID;
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    double  _finishSecs;
    unsigned long long  _finishStartTicks;
    int  _finishState;
    NSString * _homeKitSelectedRoomName;
    SFDeviceOperationHomeKitSetup * _homeKitSetupOperation;
    double  _homeKitSetupSecs;
    int  _homeKitSetupState;
    int  _homeKitUserInputState;
    NSString * _iCloudUserID;
    bool  _iTunesSignInSkip;
    NSString * _iTunesUserID;
    bool  _invalidateCalled;
    unsigned int  _pairSetupFlags;
    double  _pairSetupSecs;
    int  _pairSetupState;
    SFDevice * _peerDevice;
    unsigned long long  _peerFeatureFlags;
    int  _personalSiriChoice;
    int  _personalSiriState;
    bool  _preAuthEnabled;
    int  _preAuthState;
    bool  _prefStereoPairEnabled;
    int  _preflightAppleMusicState;
    bool  _preflightEnabled;
    int  _preflightWiFiState;
    int  _preflightiCloudState;
    int  _preflightiTunesState;
    UIViewController * _presentingViewController;
    id /* block */  _progressHandler;
    id /* block */  _promptForAppleMusicHandler;
    id /* block */  _promptForHomeHandler;
    id /* block */  _promptForPINHandler;
    id /* block */  _promptForPersonalSiriHandler;
    id /* block */  _promptForRoomHandler;
    id /* block */  _promptForSiriLanguageHandler;
    id /* block */  _promptForStereoRoleHandler;
    id /* block */  _promptForTermsHandler;
    id /* block */  _promptForiTunesSignInHandler;
    id /* block */  _promptToInstallHomeAppHandler;
    id /* block */  _promptToShareSettingsHandler;
    SFSession * _sfSession;
    bool  _sfSessionSecured;
    int  _sfSessionState;
    bool  _shareSettingsAgreed;
    int  _shareSettingsState;
    unsigned int  _siriFlags;
    NSArray * _siriLanguageCodes;
    long long  _siriLanguageIndex;
    int  _siriLanguageState;
    bool  _siriPasscodeEnabled;
    bool  _siriPasscodeInitDone;
    bool  _siriPasscodeSecured;
    int  _siriPasscodeState;
    NSString * _siriPreferredLanguage;
    unsigned long long  _startTicks;
    HMAccessory * _stereoCounterpartAccessory;
    int  _stereoPairRole;
    NSString * _stereoPairTightSyncGroupID;
    int  _stereoPairUserInputState;
    bool  _termsAgreed;
    int  _termsState;
    unsigned int  _testFlags;
    double  _totalSecs;
    bool  _touchRemoteEnabled;
    double  _trActivationSecs;
    unsigned long long  _trActivationStartTicks;
    int  _trActivationState;
    double  _trAuthenticationSecs;
    unsigned long long  _trAuthenticationStartTicks;
    int  _trAuthenticationState;
    bool  _trNeedsNetwork;
    unsigned long long  _trNetworkStartTicks;
    int  _trNetworkState;
    TROperationQueue * _trOperationQueue;
    NSMutableArray * _trOperations;
    TRSession * _trSession;
    int  _trSessionState;
    double  _trSetupConfigurationSecs;
    unsigned long long  _trSetupConfigurationStartTicks;
    int  _trSetupConfigurationState;
    NSSet * _trUnauthServices;
    bool  _wifiSetupEnabled;
    SFDeviceOperationWiFiSetup * _wifiSetupOperation;
    double  _wifiSetupSecs;
    int  _wifiSetupState;
}

@property (nonatomic, copy) NSDictionary *additionalMetrics;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) SFDevice *peerDevice;
@property (nonatomic, retain) UIViewController *presentingViewController;
@property (nonatomic, copy) id /* block */ progressHandler;
@property (nonatomic, copy) id /* block */ promptForAppleMusicHandler;
@property (nonatomic, copy) id /* block */ promptForHomeHandler;
@property (nonatomic, copy) id /* block */ promptForPINHandler;
@property (nonatomic, copy) id /* block */ promptForPersonalSiriHandler;
@property (nonatomic, copy) id /* block */ promptForRoomHandler;
@property (nonatomic, copy) id /* block */ promptForSiriLanguageHandler;
@property (nonatomic, copy) id /* block */ promptForStereoRoleHandler;
@property (nonatomic, copy) id /* block */ promptForTermsHandler;
@property (nonatomic, copy) id /* block */ promptForiTunesSignInHandler;
@property (nonatomic, copy) id /* block */ promptToInstallHomeAppHandler;
@property (nonatomic, copy) id /* block */ promptToShareSettingsHandler;
@property (readonly) Class superclass;
@property (nonatomic) unsigned int testFlags;
@property (nonatomic) bool touchRemoteEnabled;

- (void).cxx_destruct;
- (void)_activate;
- (void)_cleanup;
- (void)_cleanupSession;
- (void)_handlePeerEvent:(id)arg1 flags:(unsigned int)arg2;
- (void)_invalidate;
- (void)_logMetrics;
- (void)_playLocalSoundID:(int)arg1 remoteSoundID:(int)arg2;
- (void)_playLocalSoundID:(int)arg1 remoteSoundID:(int)arg2 completion:(id /* block */)arg3;
- (void)_promptForPINWithFlags:(unsigned int)arg1 throttleSeconds:(int)arg2;
- (void)_reportError:(id)arg1 label:(id)arg2;
- (void)_run;
- (int)_runAppleMusic;
- (int)_runAudioPasscode;
- (void)_runAudioPasscodeCleanup;
- (void)_runAudioPasscodeHandleData:(id)arg1;
- (void)_runAudioPasscodeInitRequest;
- (void)_runAudioPasscodeInitResponse:(id)arg1 error:(id)arg2;
- (void)_runAudioPasscodeStartRequest;
- (void)_runAudioPasscodeStartResponse:(id)arg1 error:(id)arg2;
- (void)_runAudioPasscodeStopRequest;
- (void)_runAudioPasscodeTimeout;
- (int)_runBasicConfig;
- (void)_runBasicConfigReceiveResponse:(id)arg1 error:(id)arg2;
- (void)_runBasicConfigSendRequest;
- (void)_runFinishResponse:(id)arg1;
- (int)_runFinishStart;
- (int)_runHomeKitSetup;
- (int)_runHomeKitUserInput;
- (int)_runPairSetup;
- (int)_runPersonalSiri;
- (int)_runPreAuth;
- (void)_runPreAuthRequest;
- (void)_runPreAuthResponse:(id)arg1 error:(id)arg2;
- (int)_runPreflightWiFi;
- (int)_runPreflightiCloud;
- (int)_runPreflightiTunes;
- (int)_runSFSessionStart;
- (int)_runShareSettings;
- (int)_runSiriLanguage;
- (int)_runSiriPasscode;
- (void)_runSiriPasscodeInitRequest;
- (void)_runSiriPasscodeInitResponse:(id)arg1 error:(id)arg2;
- (void)_runSiriPasscodeStartPairSetup;
- (int)_runStereoPairUserInput;
- (int)_runTRActivation;
- (int)_runTRAuthentication;
- (int)_runTRNetwork;
- (int)_runTRSessionStart;
- (int)_runTRSetupConfiguration;
- (int)_runTerms;
- (int)_runWiFiSetup;
- (void)_setupAudio;
- (void)_speakPasscodeWithInstructions:(id)arg1 completion:(id /* block */)arg2;
- (void)activate;
- (id)additionalMetrics;
- (void)appleMusicNext;
- (void)audioPlayerDecodeErrorDidOccur:(id)arg1 error:(id)arg2;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(bool)arg2;
- (void)audioSessionInterrupted:(id)arg1;
- (void)dealloc;
- (void)disconnect;
- (id)dispatchQueue;
- (void)homeAppInstallChoice:(bool)arg1;
- (void)homeKitSelectHome:(id)arg1;
- (void)homeKitSelectRoom:(id)arg1;
- (id)init;
- (void)invalidate;
- (void)pairSetupTryPIN:(id)arg1;
- (id)peerDevice;
- (void)personalSiriEnabled:(bool)arg1;
- (void)playAudioPasscodeAgain;
- (id)presentingViewController;
- (id /* block */)progressHandler;
- (id /* block */)promptForAppleMusicHandler;
- (id /* block */)promptForHomeHandler;
- (id /* block */)promptForPINHandler;
- (id /* block */)promptForPersonalSiriHandler;
- (id /* block */)promptForRoomHandler;
- (id /* block */)promptForSiriLanguageHandler;
- (id /* block */)promptForStereoRoleHandler;
- (id /* block */)promptForTermsHandler;
- (id /* block */)promptForiTunesSignInHandler;
- (id /* block */)promptToInstallHomeAppHandler;
- (id /* block */)promptToShareSettingsHandler;
- (void)setAdditionalMetrics:(id)arg1;
- (void)setDispatchQueue:(id)arg1;
- (void)setPeerDevice:(id)arg1;
- (void)setPresentingViewController:(id)arg1;
- (void)setProgressHandler:(id /* block */)arg1;
- (void)setPromptForAppleMusicHandler:(id /* block */)arg1;
- (void)setPromptForHomeHandler:(id /* block */)arg1;
- (void)setPromptForPINHandler:(id /* block */)arg1;
- (void)setPromptForPersonalSiriHandler:(id /* block */)arg1;
- (void)setPromptForRoomHandler:(id /* block */)arg1;
- (void)setPromptForSiriLanguageHandler:(id /* block */)arg1;
- (void)setPromptForStereoRoleHandler:(id /* block */)arg1;
- (void)setPromptForTermsHandler:(id /* block */)arg1;
- (void)setPromptForiTunesSignInHandler:(id /* block */)arg1;
- (void)setPromptToInstallHomeAppHandler:(id /* block */)arg1;
- (void)setPromptToShareSettingsHandler:(id /* block */)arg1;
- (void)setTestFlags:(unsigned int)arg1;
- (void)setTouchRemoteEnabled:(bool)arg1;
- (void)shareSettingsAgreed;
- (void)siriLanguagePicked:(long long)arg1;
- (void)skipAudioPasscode;
- (void)skipiTunesSignIn;
- (void)speakPasscodeWithCompletion:(id /* block */)arg1;
- (void)speakPasscodeWithInstructions:(id)arg1 completion:(id /* block */)arg2;
- (void)stereoRolePicked:(int)arg1;
- (void)termsAgreed;
- (unsigned int)testFlags;
- (bool)touchRemoteEnabled;

@end
