/* made by EzioChiu
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIColor : NSObject <NSCopying, NSItemProviderReading, NSItemProviderWriting, NSSecureCoding, UIItemProviderReading, UIItemProviderWriting> {
    NSString * _cachedStyleString;
    NSString * _systemColorName;
}

@property (nonatomic, readonly) struct CGColor { }*CGColor;
@property (nonatomic, readonly) CIColor *CIColor;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (getter=_systemColorName, setter=_setSystemColorName:, nonatomic, retain) NSString *systemColorName;
@property (nonatomic, readonly, copy) NSArray *writableTypeIdentifiersForItemProvider;

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

+ (id)__halfTransparentBlackColor;
+ (id)__halfTransparentWhiteColor;
+ (id)_accessibilityButtonShapesBackgroundColorOnDark;
+ (id)_accessibilityButtonShapesBackgroundColorOnLight;
+ (id)_accessibilityButtonShapesDisabledBackgroundColorOnDark;
+ (id)_accessibilityButtonShapesNoBlendModeBackgroundColorOnDark;
+ (id)_accessibilityButtonShapesNoBlendModeBackgroundColorOnLight;
+ (id)_accessibilityDarkenedColorForColor:(id)arg1;
+ (id)_alternateSystemInteractionTintColor;
+ (id)_barHairlineShadowColor;
+ (id)_barStyleBlackHairlineShadowColor;
+ (id)_composedColorFromSourceColor:(id)arg1 destinationColor:(id)arg2 tintColor:(id)arg3 alpha:(double)arg4;
+ (id)_dimmingViewColor;
+ (id)_disambiguated_due_to_CIImage_colorWithCGColor:(struct CGColor { }*)arg1;
+ (id)_disambiguated_due_to_CIImage_colorWithRed:(double)arg1 green:(double)arg2 blue:(double)arg3 alpha:(double)arg4;
+ (id)_externalBarBackgroundColor;
+ (id)_externalSystemDarkGrayColor;
+ (id)_externalSystemExtraDarkGrayColor;
+ (id)_externalSystemGrayColor;
+ (id)_externalSystemMidGrayColor;
+ (id)_externalSystemSuperDarkGrayColor;
+ (id)_grayColorForFontSize:(double)arg1;
+ (double)_luminanceWithRed:(double)arg1 green:(double)arg2 blue:(double)arg3;
+ (id)_markedTextBackgroundColor;
+ (id)_markedTextBorderColor;
+ (id)_systemColorForColor:(id)arg1 withName:(id)arg2;
+ (id)_systemColorWithName:(id)arg1;
+ (id)_systemDestructiveTintColor;
+ (id)_systemInteractionTintColor;
+ (id)_systemMidGrayTintColor;
+ (id)_systemSelectedColor;
+ (id)_translucentPaperTextureColor;
+ (id)_vibrantDarkFillDodgeColor;
+ (id)_vibrantLightDividerBurnColor;
+ (id)_vibrantLightDividerDarkeningColor;
+ (id)_vibrantLightFillBurnColor;
+ (id)_vibrantLightFillDarkeningColor;
+ (id)_vibrantLightSectionDelimiterDividerBurnColor;
+ (id)_vibrantLightSectionDelimiterDividerDarkeningColor;
+ (id)_webContentBackgroundColor;
+ (id)allocWithZone:(struct _NSZone { }*)arg1;
+ (id)blueColor;
+ (id)brownColor;
+ (id)classFallbacksForKeyedArchiver;
+ (id)clearColor;
+ (id)colorNamed:(id)arg1;
+ (id)colorNamed:(id)arg1 inBundle:(id)arg2 compatibleWithTraitCollection:(id)arg3;
+ (id)colorWithCGColor:(struct CGColor { }*)arg1;
+ (id)colorWithCIColor:(id)arg1;
+ (id)colorWithDisplayP3Red:(double)arg1 green:(double)arg2 blue:(double)arg3 alpha:(double)arg4;
+ (id)colorWithHue:(double)arg1 saturation:(double)arg2 brightness:(double)arg3 alpha:(double)arg4;
+ (id)colorWithPatternImage:(id)arg1;
+ (id)colorWithRed:(double)arg1 green:(double)arg2 blue:(double)arg3 alpha:(double)arg4;
+ (id)colorWithWhite:(double)arg1 alpha:(double)arg2;
+ (id)cyanColor;
+ (id)darkGrayColor;
+ (id)externalSystemGreenColor;
+ (id)externalSystemRedColor;
+ (id)externalSystemTealColor;
+ (id)grayColor;
+ (id)greenColor;
+ (id)infoTextOverPinStripeTextColor;
+ (void)initialize;
+ (id)insertionPointColor;
+ (id)lightGrayColor;
+ (id)lightTextColor;
+ (id)magentaColor;
+ (id)newObjectWithItemProviderData:(id)arg1 typeIdentifier:(id)arg2 options:(id)arg3 error:(id*)arg4;
+ (id)noContentDarkGradientBackgroundColor;
+ (id)noContentLightGradientBackgroundColor;
+ (id)objectWithItemProviderData:(id)arg1 typeIdentifier:(id)arg2 error:(id*)arg3;
+ (id)orangeColor;
+ (id)pinStripeColor;
+ (id)purpleColor;
+ (id)readableTypeIdentifiersForItemProvider;
+ (id)redColor;
+ (id)scrollViewTexturedBackgroundColor;
+ (id)sectionHeaderBorderColor;
+ (id)sectionHeaderOpaqueBackgroundColor;
+ (id)sectionListBorderColor;
+ (id)selectionGrabberColor;
+ (id)selectionHighlightColor;
+ (bool)supportsSecureCoding;
+ (id)systemBlueColor;
+ (id)systemDarkBlueColor;
+ (id)systemDarkGreenColor;
+ (id)systemDarkOrangeColor;
+ (id)systemDarkPinkColor;
+ (id)systemDarkRedColor;
+ (id)systemDarkTealColor;
+ (id)systemDarkYellowColor;
+ (id)systemGrayColor;
+ (id)systemGreenColor;
+ (id)systemMidGrayColor;
+ (id)systemOrangeColor;
+ (id)systemPinkColor;
+ (id)systemPurpleColor;
+ (id)systemRedColor;
+ (id)systemTealColor;
+ (id)systemYellowColor;
+ (id)tableCellBlueTextColor;
+ (id)tableCellGrayTextColor;
+ (id)tableCellGroupedBackgroundColorLegacyWhite;
+ (id)tableCellValue1BlueColor;
+ (id)tableCellValue2BlueColor;
+ (id)tableCellbackgroundColorCarPlay;
+ (id)tableGroupedSeparatorLightColor;
+ (id)tableGroupedTopShadowColor;
+ (id)tablePlainHeaderFooterBackgroundColor;
+ (id)tablePlainHeaderFooterFloatingBackgroundColor;
+ (id)tableSelectionColor;
+ (id)tableSelectionGradientEndColor;
+ (id)tableSelectionGradientStartColor;
+ (id)tableSeparatorDarkColor;
+ (id)tableSeparatorLightColor;
+ (id)tableShadowColor;
+ (id)textFieldAtomBlueColor;
+ (id)textFieldAtomPurpleColor;
+ (id)underPageBackgroundColor;
+ (id)viewFlipsideBackgroundColor;
+ (id)writableTypeIdentifiersForItemProvider;
+ (id)yellowColor;

- (void).cxx_destruct;
- (struct CGColor { }*)CGColor;
- (id)CIColor;
- (id)_colorBlendedWithColor:(id)arg1;
- (id)_colorBlendedWithColor:(id)arg1 compositingFilter:(id)arg2;
- (id)_colorBlendedWithColors:(id)arg1;
- (double)_colorDifferenceFromColor:(id)arg1;
- (bool)_getRed:(double*)arg1 green:(double*)arg2 blue:(double*)arg3 alpha:(double*)arg4;
- (bool)_getWhite:(double*)arg1 alpha:(double*)arg2;
- (bool)_isDeepColor;
- (bool)_isSimilarToColor:(id)arg1 withinPercentage:(double)arg2;
- (double)_luminance;
- (double)_luminanceDifferenceFromColor:(id)arg1;
- (void)_setSystemColorName:(id)arg1;
- (id)_systemColorName;
- (id)_ui_swipeActionHighlightedColor;
- (double)alphaComponent;
- (struct CGColor { }*)cgColor;
- (Class)classForCoder;
- (id)colorWithAlphaComponent:(double)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)encodeWithCoder:(id)arg1;
- (bool)getHue:(double*)arg1 saturation:(double*)arg2 brightness:(double*)arg3 alpha:(double*)arg4;
- (bool)getRed:(double*)arg1 green:(double*)arg2 blue:(double*)arg3 alpha:(double*)arg4;
- (bool)getWhite:(double*)arg1 alpha:(double*)arg2;
- (unsigned long long)hash;
- (id)initWithCGColor:(struct CGColor { }*)arg1;
- (id)initWithCIColor:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDisplayP3Red:(double)arg1 green:(double)arg2 blue:(double)arg3 alpha:(double)arg4;
- (id)initWithHue:(double)arg1 saturation:(double)arg2 brightness:(double)arg3 alpha:(double)arg4;
- (id)initWithItemProviderData:(id)arg1 typeIdentifier:(id)arg2 error:(id*)arg3;
- (id)initWithPatternImage:(id)arg1;
- (id)initWithRed:(double)arg1 green:(double)arg2 blue:(double)arg3 alpha:(double)arg4;
- (id)initWithWhite:(double)arg1 alpha:(double)arg2;
- (bool)isEqual:(id)arg1;
- (bool)isPatternColor;
- (id)loadDataWithTypeIdentifier:(id)arg1 forItemProviderCompletionHandler:(id /* block */)arg2;
- (void)registerLoadHandlersToItemProvider:(id)arg1;
- (void)set;
- (void)setFill;
- (void)setStroke;
- (id)styleString;
- (id)writableTypeIdentifiersForItemProvider;

// Image: /bootstrap/Library/SBInject/AnemoneColors.dylib

+ (id)_externalSystemWhiteColor;
+ (id)anem_W3CColorNames;
+ (id)anem_colorWithCSS:(id)arg1;
+ (id)anem_colorWithHSLString:(id)arg1;
+ (id)anem_colorWithHexString:(id)arg1;
+ (id)anem_colorWithRGBString:(id)arg1;
+ (id)anem_colorWithW3CNamedColor:(id)arg1;
+ (id)blackColor;
+ (id)darkTextColor;
+ (id)groupTableViewBackgroundColor;
+ (id)sectionHeaderBackgroundColor;
+ (id)tableBackgroundColor;
+ (id)tableCellBackgroundColor;
+ (id)tableCellDefaultSelectionTintColor;
+ (id)tableCellGroupedBackgroundColor;
+ (id)tableCellPlainBackgroundColor;
+ (id)whiteColor;

- (id)anem_hexStringValue;
- (id)anem_hslStringValue;
- (id)anem_rgbStringValue;
- (bool)cmr_getHue:(double*)arg1 saturation:(double*)arg2 brightness:(double*)arg3 alpha:(double*)arg4;
- (bool)cmr_getRed:(double*)arg1 green:(double*)arg2 blue:(double*)arg3 alpha:(double*)arg4;

// Image: /bootstrap/Library/SBInject/Eclipse.dylib

+ (id)amberBarColor;
+ (id)amberTableColor;
+ (id)amberViewColor;
+ (id)bambooBarColor;
+ (id)bambooTableColor;
+ (id)bambooViewColor;
+ (id)changeBrightness:(id)arg1 amount:(double)arg2;
+ (id)citrusBarColor;
+ (id)citrusTableColor;
+ (id)citrusViewColor;
+ (bool)color:(id)arg1 isEqualToColor:(id)arg2 withTolerance:(double)arg3;
+ (id)colorWithHexString:(id)arg1 alpha:(int)arg2;
+ (id)crimsonBarColor;
+ (id)crimsonTableColor;
+ (id)crimsonViewColor;
+ (id)darkerColorForColor:(id)arg1;
+ (id)darkerColorForSelectionColor:(id)arg1;
+ (id)duskBarColor;
+ (id)duskTableColor;
+ (id)duskViewColor;
+ (id)eclipseBabyBlueTintColor;
+ (bool)eclipseCustomNavColorsEnabled;
+ (bool)eclipseCustomStatusbarColorsEnabled;
+ (bool)eclipseCustomTextColorsEnabled;
+ (bool)eclipseCustomThemeColorsEnabled;
+ (bool)eclipseCustomTintColorsEnabled;
+ (id)eclipseDarkOrangeTintColor;
+ (id)eclipseGreenTintColor;
+ (id)eclipseNavHexColor;
+ (id)eclipsePinkTintColor;
+ (id)eclipsePurpleTintColor;
+ (id)eclipseRedTintColor;
+ (id)eclipseSelectedNavColor;
+ (id)eclipseSelectedStatusbarTintColor;
+ (id)eclipseSelectedTableColor;
+ (id)eclipseSelectedTextColor;
+ (id)eclipseSelectedTintColor;
+ (id)eclipseSelectedViewColor;
+ (id)eclipseStatusbarHexColor;
+ (id)eclipseTextHexColor;
+ (id)eclipseThemeHexColor;
+ (id)eclipseTintHexColor;
+ (id)eclipseWhiteTintColor;
+ (id)eclipseYellowTintColor;
+ (id)getDominantColor:(id)arg1;
+ (id)grapeBarColor;
+ (id)grapeTableColor;
+ (id)grapeViewColor;
+ (id)graphiteBarColor;
+ (id)graphiteTableColor;
+ (id)graphiteViewColor;
+ (id)jungleBarColor;
+ (id)jungleTableColor;
+ (id)jungleViewColor;
+ (id)lapisBarColor;
+ (id)lapisTableColor;
+ (id)lapisViewColor;
+ (id)midnightBarColor;
+ (id)midnightTableColor;
+ (id)midnightViewColor;
+ (id)navyBarColor;
+ (id)navyTableColor;
+ (id)navyViewColor;
+ (id)nightBarColor;
+ (id)nightTableColor;
+ (id)nightViewColor;
+ (id)rosePinkBarColor;
+ (id)rosePinkTableColor;
+ (id)rosePinkViewColor;
+ (id)saffronBarColor;
+ (id)saffronTableColor;
+ (id)saffronViewColor;
+ (id)silverBarColor;
+ (id)silverTableColor;
+ (id)silverViewColor;
+ (id)skyBarColor;
+ (id)skyTableColor;
+ (id)skyViewColor;
+ (id)violetBarColor;
+ (id)violetTableColor;
+ (id)violetViewColor;
+ (id)wineBarColor;
+ (id)wineTableColor;
+ (id)wineViewColor;

- (id)eclipsePrefs;

@end
